version: '2'

services:
  app:
    image: 'bookmyshow:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - zookeeper
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bms_db:5432/
      - SPRING_DATASOURCE_USERNAME=megha
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "8081:8080"

  db:
    image: 'postgres:latest'
    volumes:
      - ./output_file:/docker-entrypoint-initdb.d
    container_name: bms_db
    environment:
      - POSTGRES_USER=megha
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1